-- Firebird DDL for Hotel Chain System

-- Table: HOTEL
CREATE TABLE HOTEL (
    ID_HOTEL INTEGER NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    UBICACION VARCHAR(200),
    CONSTRAINT PK_HOTEL PRIMARY KEY (ID_HOTEL)
);

-- Table: HABITACION
CREATE TABLE HABITACION (
    ID_HAB INTEGER NOT NULL,
    ID_HOTEL INTEGER NOT NULL,
    TIPO VARCHAR(50),
    ESTADO VARCHAR(20),
    CONSTRAINT PK_HABITACION PRIMARY KEY (ID_HAB),
    CONSTRAINT FK_HAB_HOTEL FOREIGN KEY (ID_HOTEL) REFERENCES HOTEL (ID_HOTEL)
);

-- Table: HUESPED
CREATE TABLE HUESPED (
    ID_HUES INTEGER NOT NULL,
    ID_HOTEL INTEGER NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    DOC VARCHAR(50),
    CONSTRAINT PK_HUESPED PRIMARY KEY (ID_HUES),
    CONSTRAINT FK_HUES_HOTEL FOREIGN KEY (ID_HOTEL) REFERENCES HOTEL (ID_HOTEL)
);

-- Table: RESERVA
CREATE TABLE RESERVA (
    ID_RES INTEGER NOT NULL,
    ID_HOTEL INTEGER NOT NULL,
    ID_HUES INTEGER NOT NULL,
    ID_HAB INTEGER NOT NULL,
    FECHA_DESDE TIMESTAMP,
    FECHA_HASTA TIMESTAMP,
    CONSTRAINT PK_RESERVA PRIMARY KEY (ID_RES),
    CONSTRAINT FK_RES_HOTEL FOREIGN KEY (ID_HOTEL) REFERENCES HOTEL (ID_HOTEL),
    CONSTRAINT FK_RES_HUES FOREIGN KEY (ID_HUES) REFERENCES HUESPED (ID_HUES),
    CONSTRAINT FK_RES_HAB FOREIGN KEY (ID_HAB) REFERENCES HABITACION (ID_HAB)
);

-- Table: CONSUMO
CREATE TABLE CONSUMO (
    ID_CONS INTEGER NOT NULL,
    ID_HOTEL INTEGER NOT NULL,
    ID_RES INTEGER NOT NULL,
    DETALLE VARCHAR(200),
    MONTO DECIMAL(10, 2),
    CONSTRAINT PK_CONSUMO PRIMARY KEY (ID_CONS),
    CONSTRAINT FK_CONS_HOTEL FOREIGN KEY (ID_HOTEL) REFERENCES HOTEL (ID_HOTEL),
    CONSTRAINT FK_CONS_RES FOREIGN KEY (ID_RES) REFERENCES RESERVA (ID_RES)
);

-- Generators (Sequences)
CREATE SEQUENCE GEN_HOTEL_ID;
CREATE SEQUENCE GEN_HABITACION_ID;
CREATE SEQUENCE GEN_HUESPED_ID;
CREATE SEQUENCE GEN_RESERVA_ID;
CREATE SEQUENCE GEN_CONSUMO_ID;

-- Triggers for Auto-Increment (Optional, if application doesn't supply ID)
-- Note: In a multi-master setup, it's often better to control IDs in the app or use offset ranges manually set on the generator.
-- Below are standard triggers. The offset must be set via 'SET GENERATOR GEN_NAME TO X;' for each hotel.

SET TERM ^ ;

CREATE TRIGGER TR_HOTEL_BI FOR HOTEL
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID_HOTEL IS NULL) THEN
    NEW.ID_HOTEL = GEN_ID(GEN_HOTEL_ID, 1);
END^

CREATE TRIGGER TR_HABITACION_BI FOR HABITACION
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID_HAB IS NULL) THEN
    NEW.ID_HAB = GEN_ID(GEN_HABITACION_ID, 1);
END^

CREATE TRIGGER TR_HUESPED_BI FOR HUESPED
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID_HUES IS NULL) THEN
    NEW.ID_HUES = GEN_ID(GEN_HUESPED_ID, 1);
END^

CREATE TRIGGER TR_RESERVA_BI FOR RESERVA
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID_RES IS NULL) THEN
    NEW.ID_RES = GEN_ID(GEN_RESERVA_ID, 1);
END^

CREATE TRIGGER TR_CONSUMO_BI FOR CONSUMO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID_CONS IS NULL) THEN
    NEW.ID_CONS = GEN_ID(GEN_CONSUMO_ID, 1);
END^

SET TERM ; ^
